name: live_cell_extension
description: Generates cell property accessors for classes annotated with CellExtension from the live_cells package.
version: 0.6.2
repository: https://github.com/alex-gutev/live_cell_extension
issue_tracker: https://github.com/alex-gutev/live_cell_extension/issues

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  live_cell_annotations: ^0.5.1

  build: ^3.0.0
  source_gen: ^3.0.0
  analyzer: ^7.7.0
  code_builder: ^4.10.1

dev_dependencies:
  test:
  build_runner:
  build_verify:
  build_test:
  source_gen_test: ^1.3.0
  lints: ^3.0.0