name: live_cell_extension
description: Generates cell property accessors for classes annotated with CellExtension from the live_cells package.
version: 0.4.6
repository: https://github.com/alex-gutev/live_cell_extension
issue_tracker: https://github.com/alex-gutev/live_cell_extension/issues

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  live_cell_annotations: ^0.4.0
  live_cells_core: ^0.15.0

  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.2.0

dev_dependencies:
  test:
  build_runner:
  build_verify:
  build_test:
  source_gen_test: ^1.0.6
